// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTfbheyd2JbswdDD3dy4WNYt-_nkzm9e4',
    appId: '1:172757776620:web:61f350f2daff524ad00dc9',
    messagingSenderId: '172757776620',
    projectId: 'd3d-market-scanner1',
    authDomain: 'd3d-market-scanner1.firebaseapp.com',
    storageBucket: 'd3d-market-scanner1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzlBejeI54F2WEdSY3VvV5wtFV-m4v3Hk',
    appId: '1:172757776620:android:a798e5ff347ad047d00dc9',
    messagingSenderId: '172757776620',
    projectId: 'd3d-market-scanner1',
    storageBucket: 'd3d-market-scanner1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYsROBAM8YFyuWu39WbvlXaDfoF_Q3I8s',
    appId: '1:172757776620:ios:f476a8d9fe3b825cd00dc9',
    messagingSenderId: '172757776620',
    projectId: 'd3d-market-scanner1',
    storageBucket: 'd3d-market-scanner1.appspot.com',
    iosClientId: '172757776620-agoj2q00mlgjbscj7iig5stjkf65do75.apps.googleusercontent.com',
    iosBundleId: 'com.example.d3dMarketScannerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYsROBAM8YFyuWu39WbvlXaDfoF_Q3I8s',
    appId: '1:172757776620:ios:f476a8d9fe3b825cd00dc9',
    messagingSenderId: '172757776620',
    projectId: 'd3d-market-scanner1',
    storageBucket: 'd3d-market-scanner1.appspot.com',
    iosClientId: '172757776620-agoj2q00mlgjbscj7iig5stjkf65do75.apps.googleusercontent.com',
    iosBundleId: 'com.example.d3dMarketScannerApp',
  );
}
